name = "apple-actively-exploited"
main = "./src/index.ts"
compatibility_date = "2023-02-14"
kv_namespaces = [
	{ binding = "STORE", id = "a476820b18274efe9725084c887b1328", preview_id = "4f5fc7cddf464ad58347412f4681dfb7" }
]

[triggers]
crons = ["*/15 * * * *"]